/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ChapterSchema extends BaseModel {
  static $columns = [
    'courseId',
    'createdAt',
    'id',
    'key',
    'position',
    'summary',
    'title',
    'updatedAt',
  ] as const
  $columns = ChapterSchema.$columns
  @column()
  declare courseId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare position: number
  @column()
  declare summary: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConceptLinkSchema extends BaseModel {
  static $columns = ['fromConceptId', 'id', 'label', 'toConceptId'] as const
  $columns = ConceptLinkSchema.$columns
  @column()
  declare fromConceptId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column()
  declare toConceptId: number
}

export class ConceptSchema extends BaseModel {
  static $columns = [
    'chapterId',
    'createdAt',
    'explanation',
    'id',
    'key',
    'masteryState',
    'position',
    'title',
    'updatedAt',
  ] as const
  $columns = ConceptSchema.$columns
  @column()
  declare chapterId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare explanation: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare masteryState: string
  @column()
  declare position: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourseSourceSchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'id', 'reference', 'title', 'type'] as const
  $columns = CourseSourceSchema.$columns
  @column()
  declare courseId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reference: string | null
  @column()
  declare title: string
  @column()
  declare type: string
}

export class CourseSchema extends BaseModel {
  static $columns = [
    'activatedAt',
    'createdAt',
    'description',
    'id',
    'importVersion',
    'status',
    'subjectId',
    'targetDate',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = CourseSchema.$columns
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare importVersion: number
  @column()
  declare status: string
  @column()
  declare subjectId: number | null
  @column.date()
  declare targetDate: DateTime | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class DailyAvailabilitySchema extends BaseModel {
  static $columns = ['dayOfWeek', 'id', 'minutes', 'userId'] as const
  $columns = DailyAvailabilitySchema.$columns
  @column()
  declare dayOfWeek: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minutes: number
  @column()
  declare userId: number
}

export class FlashcardSchema extends BaseModel {
  static $columns = [
    'back',
    'conceptId',
    'courseSourceId',
    'createdAt',
    'dueAt',
    'front',
    'id',
    'intervalDays',
    'lapses',
    'lastReviewedAt',
    'repetitions',
    'reversible',
    'type',
    'updatedAt',
  ] as const
  $columns = FlashcardSchema.$columns
  @column()
  declare back: string
  @column()
  declare conceptId: number
  @column()
  declare courseSourceId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dueAt: DateTime | null
  @column()
  declare front: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare intervalDays: number
  @column()
  declare lapses: number
  @column.dateTime()
  declare lastReviewedAt: DateTime | null
  @column()
  declare repetitions: number
  @column()
  declare reversible: boolean
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GoogleCalendarConnectionSchema extends BaseModel {
  static $columns = [
    'calendarId',
    'createdAt',
    'id',
    'lastSyncedAt',
    'refreshTokenEncrypted',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = GoogleCalendarConnectionSchema.$columns
  @column()
  declare calendarId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare refreshTokenEncrypted: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ReviewAttemptSchema extends BaseModel {
  static $columns = [
    'feedbackJson',
    'flashcardId',
    'grade',
    'id',
    'responseJson',
    'reviewedAt',
    'score',
    'selfTestId',
    'userId',
  ] as const
  $columns = ReviewAttemptSchema.$columns
  @column()
  declare feedbackJson: string | null
  @column()
  declare flashcardId: number | null
  @column()
  declare grade: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare responseJson: string | null
  @column.dateTime()
  declare reviewedAt: DateTime
  @column()
  declare score: number | null
  @column()
  declare selfTestId: number | null
  @column()
  declare userId: number
}

export class SelfTestSchema extends BaseModel {
  static $columns = [
    'conceptId',
    'createdAt',
    'difficulty',
    'expectedAnswerJson',
    'explanation',
    'id',
    'optionsJson',
    'position',
    'prompt',
    'type',
    'updatedAt',
  ] as const
  $columns = SelfTestSchema.$columns
  @column()
  declare conceptId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare difficulty: number
  @column()
  declare expectedAnswerJson: string
  @column()
  declare explanation: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare optionsJson: string | null
  @column()
  declare position: number
  @column()
  declare prompt: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudySessionSchema extends BaseModel {
  static $columns = [
    'completedAt',
    'courseId',
    'createdAt',
    'durationMinutes',
    'googleEventId',
    'id',
    'plannedFor',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = StudySessionSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare courseId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMinutes: number
  @column()
  declare googleEventId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare plannedFor: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SubjectSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = SubjectSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
